name: Build grpc wheel on Power

on:
  workflow_dispatch:
    inputs:
      release:
        required: true
        type: string
  workflow_call:
    inputs:
      release:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms:  "linux/ppc64le"

      - name: Install
        id: install
        run: >-
          docker run
          --rm
          --platform "linux/ppc64le"
          --mount "type=bind,src=$(pwd),dst=/build"
          -w "/build"
          "quay.io/raja0940/types-test:v3.9.17"
          /bin/bash -ec '
          source ~/.profile;
          pyenv global 3.9.17;
          pip install -U pip setuptools wheel Cython==3.0.0a9 launchpadlib==1.11.0 --ignore-installed;
          pip install grpcio==1.53.0 --ignore-installed;
          WHEEL_PATH=$(find /root/.cache/pip/wheels/ -name "grpcio*.whl");
          cp $WHEEL_PATH /build/;'          

      - name: Create a tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git tag ${{ inputs.release }}
          git push origin ${{ inputs.release }} -f

      - name: Capture the file
        id: capture
        run: |
          WHEEL_PATH=$(find $PWD -name "grpcio*.whl")
          echo "Found $WHEEL_PATH"
          echo "ARTIFACT=$WHEEL_PATH" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ inputs.release }}
          tag_name: ${{ inputs.release }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ steps.capture.outputs.ARTIFACT }}
          draft: false
          prerelease: false
